"""D2-05 optional "Relevance to this assignment" notes.

One short note per experience row: why one recorded reference relates to one
shortlisting criterion. Generated by the analysis provider's short-route model,
then checked deterministically: every number, year, currency code, percentage
and capitalized multi-word name in the note must appear in the inputs, and the
note may not claim compliance or verification. A note that fails is dropped and
counted; the draft renders without it. Budgets bound the whole step.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
import logging
import re
import time
from typing import Any, Awaitable, Callable

logger = logging.getLogger(__name__)

NOTE_CONCURRENCY = 4
NOTE_TIMEOUT_SECONDS = 20.0
NOTE_BUDGET_SECONDS = 45.0
NOTE_MAX_CHARACTERS = 500
NOTE_MAX_OUTPUT_TOKENS = 1024

SYSTEM_PROMPT = """You write a short note for an Expression of Interest. Given one
shortlisting criterion and one past assignment recorded by the firm, write one or
two plain sentences on how that assignment relates to the criterion. Use only the
facts given. Do not add names, numbers, dates, places or claims that are not in the
input. Never state that the firm is compliant, meets, satisfies or qualifies for the
criterion, and never call anything verified or guaranteed. Return the sentences only."""

_LANGUAGE_INSTRUCTION = {
    "en": "Write in English.",
    "ru": "Write in Russian. Keep names, numbers and codes exactly as given.",
}

_NUMBER = re.compile(r"\d+(?:[.,]\d+)*")  # thousands separators and decimals, never across lines
_CURRENCY = re.compile(r"\b[A-Z]{3}\b")
_CAPITALIZED_RUN = re.compile(
    r"[A-ZА-ЯЁ][\w'’.-]*(?:[ \t]+(?:of|and|the|for|de|и|по)?[ \t]*[A-ZА-ЯЁ][\w'’.-]*)+"
)
_FORBIDDEN = re.compile(
    r"complian|\bmeets?\b|\bmet\b|satisf|qualif|verif|guarant|certif|"
    r"соответству|отвечает требован|удовлетворя|квалифицир|подтвержд|гарант",
    re.IGNORECASE,
)


_LEADING_WORDS = frozenset({
    "the", "this", "that", "a", "an", "our", "its", "in", "for", "with", "under", "as", "both",
    "этот", "эта", "это", "данный", "данная", "в", "для", "по", "наш", "наша",
})


_CONNECTORS = frozenset({"of", "and", "the", "for", "de", "и", "по"})


def _normalized_number(value: str) -> str:
    digits = re.sub(r"[\s,]", "", value)
    if "." in digits:
        digits = digits.rstrip("0").rstrip(".")
    return digits


def _numbers(text: str) -> set[str]:
    return {_normalized_number(match) for match in _NUMBER.findall(text)}


def _squash(text: str) -> str:
    return " ".join(text.split()).casefold()


@dataclass(frozen=True)
class NoteRequest:
    key: int  # experience row number
    criterion_id: str
    criterion_statement: str
    reference: dict[str, Any]
    language: str

    def input_text(self) -> str:
        fields = (
            "project_name", "client_name", "country", "sector", "service", "role", "relevant_scope",
            "start_date", "completion_date", "completion_state", "contract_value", "contract_currency",
            "contract_share_percent",
        )
        values = [self.criterion_statement] + [str(self.reference.get(name) or "") for name in fields]
        return "\n".join(value for value in values if value)

    def prompt(self) -> str:
        lines = [
            _LANGUAGE_INSTRUCTION.get(self.language, _LANGUAGE_INSTRUCTION["en"]),
            "CRITERION:", self.criterion_statement,
            "RECORDED ASSIGNMENT:",
        ]
        for name in ("project_name", "client_name", "country", "sector", "service", "role",
                     "start_date", "completion_date", "completion_state", "relevant_scope"):
            value = self.reference.get(name)
            if value:
                lines.append(f"{name}: {value}")
        return "\n".join(lines)


def validate_note(note: str | None, inputs: str) -> str | None:
    """The note when every checkable token is grounded in the inputs; otherwise None."""
    if not note:
        return None
    text = " ".join(note.split()).strip().strip('"').strip()
    if not text or len(text) > NOTE_MAX_CHARACTERS:
        return None
    if len(re.findall(r"[.!?](?:\s|$)", text)) > 2:
        return None
    if _FORBIDDEN.search(text):
        return None
    if not _numbers(text) <= _numbers(inputs):
        return None
    if not set(_CURRENCY.findall(text)) <= set(_CURRENCY.findall(inputs)):
        return None
    haystack = _squash(inputs)
    for match in _CAPITALIZED_RUN.finditer(text):
        run = match.group(0)
        # The first word of a sentence is capitalized because it starts the sentence.
        if re.search(r"(?:^|[.!?]\s+)$", text[:match.start()]):
            run = run.split(maxsplit=1)[1] if len(run.split()) > 1 else ""
        if run and not _grounded_run(run, haystack):
            return None
    return text


def _grounded_run(run: str, haystack: str) -> bool:
    """A capitalized multi-word name is grounded when it appears in the inputs.

    A sentence may open with an article or a capitalized word before a name ("The
    Navoi ...", "Work for National Grid"): the run is split at connector words and
    every multi-word part must appear; a run of single words joined by connectors
    ("Ministry of Energy") must appear as a whole.
    """
    words = run.rstrip(".").split()
    while len(words) > 1 and words[0].casefold() in _LEADING_WORDS:
        words = words[1:]
    if len(words) < 2 or _squash(" ".join(words)) in haystack:
        return True
    segments: list[list[str]] = [[]]
    for word in words:
        if word.casefold() in _CONNECTORS:
            segments.append([])
        else:
            segments[-1].append(word)
    multi = [segment for segment in segments if len(segment) > 1]
    if not multi:
        return False
    return all(_squash(" ".join(segment)) in haystack for segment in multi)


@dataclass
class NoteOutcome:
    notes: dict[int, str] = field(default_factory=dict)
    generated: int = 0
    dropped: int = 0


ProviderCall = Callable[[NoteRequest], Awaitable[str]]


async def generate_relevance_notes(
    requests: list[NoteRequest],
    call: ProviderCall | None = None,
    *,
    concurrency: int | None = None,
    timeout_seconds: float | None = None,
    budget_seconds: float | None = None,
) -> NoteOutcome:
    """Generate and validate notes; anything not finished inside the budget is dropped."""
    outcome = NoteOutcome()
    if not requests:
        return outcome
    concurrency = concurrency or NOTE_CONCURRENCY
    timeout_seconds = timeout_seconds or NOTE_TIMEOUT_SECONDS
    budget_seconds = budget_seconds or NOTE_BUDGET_SECONDS
    call = call or gemini_note_call
    semaphore = asyncio.Semaphore(concurrency)
    started = time.monotonic()

    async def one(request: NoteRequest) -> tuple[NoteRequest, str | None]:
        async with semaphore:
            remaining = budget_seconds - (time.monotonic() - started)
            if remaining <= 0:
                return request, None
            try:
                raw = await asyncio.wait_for(call(request), timeout=min(timeout_seconds, remaining))
            except Exception as exc:  # timeout, provider error, missing key: the draft renders without it
                logger.warning("eoi_relevance_note_failed error=%s", type(exc).__name__)
                return request, None
            return request, validate_note(raw, request.input_text())

    tasks = [asyncio.create_task(one(request)) for request in requests]
    done, pending = await asyncio.wait(tasks, timeout=budget_seconds)
    for task in pending:
        task.cancel()
    for task in done:
        request, note = task.result()
        if note:
            outcome.notes[request.key] = note
            outcome.generated += 1
    outcome.dropped = len(requests) - outcome.generated
    return outcome


async def gemini_note_call(request: NoteRequest) -> str:
    """One provider call on the analysis short route, through the existing timeout client."""
    from google.genai import types

    from app.core.agents import pursuit_analyzer
    from app.core.agents.requirement_extractor import _resolve_gemini_api_key

    api_key = _resolve_gemini_api_key()
    if not api_key:
        raise RuntimeError("provider key is not configured")

    def run() -> str:
        client = pursuit_analyzer._TimeoutClient(
            api_key=api_key, http_options={"timeout": int(NOTE_TIMEOUT_SECONDS)},
        )
        response = client.models.generate_content(
            model=pursuit_analyzer.MODEL_NAME,
            contents=request.prompt(),
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT, temperature=0.0, max_output_tokens=NOTE_MAX_OUTPUT_TOKENS,
            ),
        )
        return (getattr(response, "text", "") or "").strip()

    return await asyncio.to_thread(run)
