"""add_content_hash_and_analysis_id_isolation

Revision ID: 14c7b4cac4ea
Revises: 65c42c5b80fa
Create Date: 2026-03-04 09:04:13.997258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c7b4cac4ea'
down_revision: Union[str, None] = '65c42c5b80fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_override_logs', sa.Column('analysis_id', sa.UUID(), nullable=True))
    op.create_index('ix_risk_override_logs_analysis_id', 'risk_override_logs', ['analysis_id'], unique=False)
    op.create_foreign_key(None, 'risk_override_logs', 'tender_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.add_column('tender_analyses', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_analyses', 'content_hash')
    op.drop_constraint(None, 'risk_override_logs', type_='foreignkey')
    op.drop_index('ix_risk_override_logs_analysis_id', table_name='risk_override_logs')
    op.drop_column('risk_override_logs', 'analysis_id')
    # ### end Alembic commands ###
