"""W7 evidence-backed team scenarios

Revision ID: 20260930_0001_w7_team_scenarios
Revises: 20260929_0001_w6_participation
Create Date: 2026-09-26 18:31:47.786762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260930_0001_w7_team_scenarios'
down_revision: Union[str, None] = '20260929_0001_w6_participation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_candidate_match_id_gap', 'candidate_matches', ['id', 'gap_id'])
    op.create_unique_constraint('uq_participation_record_id_match', 'candidate_participation_records', ['id', 'candidate_match_id'])
    op.create_unique_constraint('uq_pursuit_gap_id_analysis', 'pursuit_analysis_gaps', ['id', 'analysis_run_id'])
    op.create_table('team_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('pursuit_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('created_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(trim(title)) BETWEEN 1 AND 300', name='ck_team_scenario_title'),
    sa.ForeignKeyConstraint(['created_by_membership_id', 'organization_id'], ['memberships.id', 'memberships.organization_id'], name='fk_team_scenario_actor_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pursuit_id', 'organization_id'], ['organization_pursuits.id', 'organization_pursuits.organization_id'], name='fk_team_scenario_pursuit_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_team_scenario_id_organization')
    )
    op.create_index('ix_team_scenarios_pursuit_created', 'team_scenarios', ['organization_id', 'pursuit_id', 'created_at'], unique=False)
    op.create_table('team_scenario_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('analysis_pack_id', sa.UUID(), nullable=False),
    sa.Column('created_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('selection_sha256', sa.String(length=64), nullable=False),
    sa.Column('assessment_schema_version', sa.String(length=100), nullable=False),
    sa.Column('assessment_state', sa.String(length=30), nullable=False),
    sa.Column('gap_count', sa.Integer(), nullable=False),
    sa.Column('covered_gap_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_gap_count', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_participant_count', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('blocking_issue_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_later_stage_count', sa.Integer(), nullable=False),
    sa.Column('source_provenance_count', sa.Integer(), nullable=False),
    sa.Column('private_provenance_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assessment_state IN ('DRAFT', 'NEEDS_REVIEW', 'BLOCKED', 'VIABLE')", name='ck_team_revision_assessment'),
    sa.CheckConstraint("selection_sha256 ~ '^[0-9a-f]{64}$'", name='ck_team_revision_selection_sha'),
    sa.CheckConstraint('gap_count >= 0 AND covered_gap_count >= 0 AND unresolved_gap_count >= 0 AND participant_count >= 0 AND confirmed_participant_count >= 0 AND issue_count >= 0 AND blocking_issue_count >= 0 AND unresolved_later_stage_count >= 0 AND source_provenance_count >= 0 AND private_provenance_count >= 0', name='ck_team_revision_counts'),
    sa.CheckConstraint('version_number >= 1', name='ck_team_revision_version'),
    sa.ForeignKeyConstraint(['analysis_pack_id'], ['pursuit_analysis_packs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['pursuit_analysis_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_membership_id', 'organization_id'], ['memberships.id', 'memberships.organization_id'], name='fk_team_revision_actor_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_id', 'organization_id'], ['team_scenarios.id', 'team_scenarios.organization_id'], name='fk_team_revision_scenario_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'analysis_run_id', name='uq_team_revision_id_analysis'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_team_scenario_revision_id_organization'),
    sa.UniqueConstraint('id', 'scenario_id', 'organization_id', name='uq_team_revision_id_scenario_organization'),
    sa.UniqueConstraint('scenario_id', 'version_number', name='uq_team_scenario_revision_version')
    )
    op.create_index('ix_team_revisions_scenario_version', 'team_scenario_revisions', ['scenario_id', 'version_number'], unique=False)
    op.create_table('team_scenario_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('actor_membership_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('explicit_confirmation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision <> 'APPROVED_FOR_PROPOSAL' OR explicit_confirmation", name='ck_team_decision_approval_confirmation'),
    sa.CheckConstraint("decision IN ('PREFERRED', 'REJECTED', 'APPROVED_FOR_PROPOSAL')", name='ck_team_decision_value'),
    sa.CheckConstraint('length(trim(reason)) >= 3', name='ck_team_decision_reason'),
    sa.ForeignKeyConstraint(['actor_membership_id', 'organization_id'], ['memberships.id', 'memberships.organization_id'], name='fk_team_decision_actor_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'scenario_id', 'organization_id'], ['team_scenario_revisions.id', 'team_scenario_revisions.scenario_id', 'team_scenario_revisions.organization_id'], name='fk_team_decision_revision_scenario_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_id', 'organization_id'], ['team_scenarios.id', 'team_scenarios.organization_id'], name='fk_team_decision_scenario_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_decisions_scenario_created', 'team_scenario_decisions', ['scenario_id', 'created_at'], unique=False)
    op.create_table('team_scenario_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('participant_type', sa.String(length=30), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('expert_id', sa.UUID(), nullable=True),
    sa.Column('display_name_snapshot', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(participant_type = 'PARTNER_FIRM' AND firm_id IS NOT NULL AND expert_id IS NULL) OR (participant_type = 'EXPERT' AND expert_id IS NOT NULL AND firm_id IS NULL)", name='ck_team_participant_identity'),
    sa.ForeignKeyConstraint(['expert_id'], ['candidate_experts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['firm_id'], ['candidate_firms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'organization_id'], ['team_scenario_revisions.id', 'team_scenario_revisions.organization_id'], name='fk_team_participant_revision_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'revision_id', name='uq_team_participant_id_revision'),
    sa.UniqueConstraint('revision_id', 'expert_id', name='uq_team_participant_revision_expert'),
    sa.UniqueConstraint('revision_id', 'firm_id', name='uq_team_participant_revision_firm')
    )
    op.create_index('ix_team_participants_revision', 'team_scenario_participants', ['revision_id'], unique=False)
    op.create_table('team_scenario_gap_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('gap_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('review_assertion_id', sa.UUID(), nullable=True),
    sa.Column('w4_coverage_state_snapshot', sa.String(length=40), nullable=False),
    sa.Column('w4_review_state_snapshot', sa.String(length=30), nullable=False),
    sa.Column('resolution_category_snapshot', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('is_current_stage', sa.Boolean(), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('rationale_code', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('COVERED', 'PARTIAL', 'UNRESOLVED', 'BLOCKED', 'NEEDS_REVIEW')", name='ck_team_gap_state'),
    sa.CheckConstraint('(requirement_id IS NOT NULL) <> (position_id IS NOT NULL)', name='ck_team_gap_target'),
    sa.ForeignKeyConstraint(['gap_id', 'analysis_run_id'], ['pursuit_analysis_gaps.id', 'pursuit_analysis_gaps.analysis_run_id'], name='fk_team_gap_analysis', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gap_id'], ['pursuit_analysis_gaps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['pursuit_analysis_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_assertion_id'], ['pursuit_analysis_review_assertions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['pursuit_analysis_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'analysis_run_id'], ['team_scenario_revisions.id', 'team_scenario_revisions.analysis_run_id'], name='fk_team_gap_revision_analysis', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'organization_id'], ['team_scenario_revisions.id', 'team_scenario_revisions.organization_id'], name='fk_team_gap_revision_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'gap_id', name='uq_team_gap_assessment_revision_gap')
    )
    op.create_index('ix_team_gap_assessments_revision', 'team_scenario_gap_assessments', ['revision_id', 'state'], unique=False)
    op.create_table('team_scenario_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('candidate_match_id', sa.UUID(), nullable=False),
    sa.Column('participation_record_id', sa.UUID(), nullable=False),
    sa.Column('gap_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('shortlist_decision_id', sa.UUID(), nullable=False),
    sa.Column('shortlist_decision_state_snapshot', sa.String(length=30), nullable=False),
    sa.Column('proposed_contribution_snapshot', sa.Text(), nullable=False),
    sa.Column('contribution_rule_snapshot', sa.Text(), nullable=False),
    sa.Column('qualification_state_snapshot', sa.String(length=40), nullable=False),
    sa.Column('candidate_evidence_state_snapshot', sa.String(length=30), nullable=False),
    sa.Column('evidence_identities_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strongest_evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('availability_fact_id', sa.UUID(), nullable=True),
    sa.Column('availability_recorded_state', sa.String(length=30), nullable=True),
    sa.Column('availability_effective_state', sa.String(length=30), nullable=True),
    sa.Column('availability_window_start', sa.Date(), nullable=True),
    sa.Column('availability_window_end', sa.Date(), nullable=True),
    sa.Column('availability_effort_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('availability_capacity_snapshot', sa.Text(), nullable=True),
    sa.Column('availability_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interest_fact_id', sa.UUID(), nullable=True),
    sa.Column('interest_recorded_state', sa.String(length=30), nullable=True),
    sa.Column('interest_effective_state', sa.String(length=30), nullable=True),
    sa.Column('interest_conditions_snapshot', sa.Text(), nullable=True),
    sa.Column('participation_decision_id', sa.UUID(), nullable=True),
    sa.Column('participation_recorded_state', sa.String(length=30), nullable=True),
    sa.Column('participation_effective_state', sa.String(length=30), nullable=True),
    sa.Column('confirmation_source_snapshot', sa.String(length=40), nullable=True),
    sa.Column('confirmation_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconfirm_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_conditions_snapshot', sa.Text(), nullable=True),
    sa.Column('assignment_dates_snapshot', sa.Text(), nullable=True),
    sa.Column('assignment_window_result', sa.String(length=30), nullable=False),
    sa.Column('upstream_stale_snapshot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assignment_window_result IN ('FULL_WINDOW','PARTIAL_WINDOW','NO_OVERLAP','UNKNOWN_DATES')", name='ck_team_contribution_window'),
    sa.CheckConstraint('(requirement_id IS NOT NULL) <> (position_id IS NOT NULL)', name='ck_team_contribution_target'),
    sa.CheckConstraint('availability_effort_percent IS NULL OR (availability_effort_percent >= 0 AND availability_effort_percent <= 100)', name='ck_team_contribution_effort'),
    sa.ForeignKeyConstraint(['availability_fact_id', 'participation_record_id'], ['candidate_availability_facts.id', 'candidate_availability_facts.participation_record_id'], name='fk_team_contribution_availability_record', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_match_id', 'gap_id'], ['candidate_matches.id', 'candidate_matches.gap_id'], name='fk_team_contribution_match_gap', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gap_id', 'analysis_run_id'], ['pursuit_analysis_gaps.id', 'pursuit_analysis_gaps.analysis_run_id'], name='fk_team_contribution_gap_analysis', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gap_id'], ['pursuit_analysis_gaps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interest_fact_id', 'participation_record_id'], ['candidate_interest_facts.id', 'candidate_interest_facts.participation_record_id'], name='fk_team_contribution_interest_record', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_id', 'revision_id'], ['team_scenario_participants.id', 'team_scenario_participants.revision_id'], name='fk_team_contribution_participant_revision', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participation_decision_id', 'participation_record_id'], ['candidate_participation_decisions.id', 'candidate_participation_decisions.participation_record_id'], name='fk_team_contribution_decision_record', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participation_record_id', 'candidate_match_id'], ['candidate_participation_records.id', 'candidate_participation_records.candidate_match_id'], name='fk_team_contribution_participation_match', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['pursuit_analysis_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['pursuit_analysis_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'analysis_run_id'], ['team_scenario_revisions.id', 'team_scenario_revisions.analysis_run_id'], name='fk_team_contribution_revision_analysis', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'organization_id'], ['team_scenario_revisions.id', 'team_scenario_revisions.organization_id'], name='fk_team_contribution_revision_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shortlist_decision_id', 'candidate_match_id'], ['candidate_review_decisions.id', 'candidate_review_decisions.candidate_match_id'], name='fk_team_contribution_shortlist_match', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'revision_id', name='uq_team_contribution_id_revision'),
    sa.UniqueConstraint('revision_id', 'candidate_match_id', name='uq_team_contribution_revision_match')
    )
    op.create_index('ix_team_contributions_revision_gap', 'team_scenario_contributions', ['revision_id', 'gap_id'], unique=False)
    op.create_table('team_scenario_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('issue_code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('gap_id', sa.UUID(), nullable=True),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('contribution_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('REVIEW', 'BLOCKING')", name='ck_team_issue_severity'),
    sa.CheckConstraint('length(trim(issue_code)) >= 3', name='ck_team_issue_code'),
    sa.ForeignKeyConstraint(['contribution_id', 'revision_id'], ['team_scenario_contributions.id', 'team_scenario_contributions.revision_id'], name='fk_team_issue_contribution_revision', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gap_id'], ['pursuit_analysis_gaps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_id', 'revision_id'], ['team_scenario_participants.id', 'team_scenario_participants.revision_id'], name='fk_team_issue_participant_revision', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'organization_id'], ['team_scenario_revisions.id', 'team_scenario_revisions.organization_id'], name='fk_team_issue_revision_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_issues_revision', 'team_scenario_issues', ['revision_id', 'severity', 'issue_code'], unique=False)
    op.execute("""
        CREATE OR REPLACE FUNCTION reject_w7_immutable_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'W7 scenario history is append-only';
        END;
        $$
    """)
    for table in (
        'team_scenario_revisions', 'team_scenario_participants',
        'team_scenario_contributions', 'team_scenario_gap_assessments',
        'team_scenario_issues', 'team_scenario_decisions',
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_w7_immutable_mutation()"
        )
    op.execute(
        "CREATE TRIGGER trg_team_scenarios_no_delete BEFORE DELETE ON team_scenarios "
        "FOR EACH ROW EXECUTE FUNCTION reject_w7_immutable_mutation()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS trg_team_scenarios_no_delete ON team_scenarios')
    for table in (
        'team_scenario_revisions', 'team_scenario_participants',
        'team_scenario_contributions', 'team_scenario_gap_assessments',
        'team_scenario_issues', 'team_scenario_decisions',
    ):
        op.execute(f'DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}')
    op.drop_index('ix_team_issues_revision', table_name='team_scenario_issues')
    op.drop_table('team_scenario_issues')
    op.drop_index('ix_team_contributions_revision_gap', table_name='team_scenario_contributions')
    op.drop_table('team_scenario_contributions')
    op.drop_index('ix_team_gap_assessments_revision', table_name='team_scenario_gap_assessments')
    op.drop_table('team_scenario_gap_assessments')
    op.drop_index('ix_team_participants_revision', table_name='team_scenario_participants')
    op.drop_table('team_scenario_participants')
    op.drop_index('ix_team_decisions_scenario_created', table_name='team_scenario_decisions')
    op.drop_table('team_scenario_decisions')
    op.drop_index('ix_team_revisions_scenario_version', table_name='team_scenario_revisions')
    op.drop_table('team_scenario_revisions')
    op.drop_index('ix_team_scenarios_pursuit_created', table_name='team_scenarios')
    op.drop_table('team_scenarios')
    op.execute('DROP FUNCTION IF EXISTS reject_w7_immutable_mutation()')
    op.drop_constraint('uq_pursuit_gap_id_analysis', 'pursuit_analysis_gaps', type_='unique')
    op.drop_constraint('uq_participation_record_id_match', 'candidate_participation_records', type_='unique')
    op.drop_constraint('uq_candidate_match_id_gap', 'candidate_matches', type_='unique')
    # ### end Alembic commands ###
