"""w4 sealed pursuit analysis

Revision ID: 20260927_0001_w4_pursuit_analysis
Revises: 20260926_0001_w3_private_documents
Create Date: 2026-09-26 03:41:56.572024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260927_0001_w4_pursuit_analysis'
down_revision: Union[str, None] = '20260926_0001_w3_private_documents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pursuit_analysis_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('pursuit_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('candidate_sha256', sa.String(length=64), nullable=False),
    sa.Column('selected_pack_sha256', sa.String(length=64), nullable=False),
    sa.Column('analysis_language', sa.String(length=8), nullable=False),
    sa.Column('admission_decision', sa.String(length=20), nullable=False),
    sa.Column('total_known_pages', sa.Integer(), nullable=False),
    sa.Column('page_count_known', sa.Boolean(), nullable=False),
    sa.Column('page_limit', sa.Integer(), nullable=False),
    sa.Column('alternate_character_count', sa.Integer(), nullable=False),
    sa.Column('alternate_character_limit', sa.Integer(), nullable=False),
    sa.Column('limit_disclosure', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("admission_decision = 'ADMITTED'", name='ck_analysis_pack_admitted'),
    sa.CheckConstraint("analysis_language IN ('en','uz','ru')", name='ck_analysis_pack_language'),
    sa.CheckConstraint("candidate_sha256 ~ '^[0-9a-f]{64}$'", name='ck_analysis_pack_candidate_sha'),
    sa.CheckConstraint("selected_pack_sha256 ~ '^[0-9a-f]{64}$'", name='ck_analysis_pack_selected_sha'),
    sa.CheckConstraint('alternate_character_count >= 0 AND alternate_character_limit > 0', name='ck_analysis_pack_alternate_limit'),
    sa.CheckConstraint('total_known_pages >= 0 AND page_limit = 500', name='ck_analysis_pack_page_limit'),
    sa.ForeignKeyConstraint(['pursuit_id', 'organization_id'], ['organization_pursuits.id', 'organization_pursuits.organization_id'], name='fk_analysis_pack_pursuit_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_membership_id', 'organization_id'], ['memberships.id', 'memberships.organization_id'], name='fk_analysis_pack_requester_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_packs_pursuit_created', 'pursuit_analysis_packs', ['pursuit_id', 'created_at'], unique=False)
    op.create_table('pursuit_analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('pursuit_id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('analysis_language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_completeness', sa.String(length=30), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_sha256', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('pipeline_version', sa.String(length=100), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('dispatch_attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_dispatch_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=200), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_stage', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("analysis_language IN ('en','uz','ru')", name='ck_analysis_run_language'),
    sa.CheckConstraint("prompt_sha256 ~ '^[0-9a-f]{64}$'", name='ck_analysis_run_prompt_sha'),
    sa.CheckConstraint("result_completeness IS NULL OR result_completeness = 'FULL'", name='ck_analysis_run_completeness'),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','COMPLETED','FAILED')", name='ck_analysis_run_status'),
    sa.CheckConstraint('attempt_count >= 0 AND max_attempts BETWEEN 1 AND 10 AND dispatch_attempt_count >= 0', name='ck_analysis_run_attempts'),
    sa.ForeignKeyConstraint(['pack_id'], ['pursuit_analysis_packs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pursuit_id', 'organization_id'], ['organization_pursuits.id', 'organization_pursuits.organization_id'], name='fk_analysis_run_pursuit_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_membership_id', 'organization_id'], ['memberships.id', 'memberships.organization_id'], name='fk_analysis_run_requester_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id')
    )
    op.create_index('ix_analysis_runs_dispatch', 'pursuit_analysis_runs', ['status', 'next_dispatch_at'], unique=False)
    op.create_index('ix_analysis_runs_pursuit_created', 'pursuit_analysis_runs', ['pursuit_id', 'created_at'], unique=False)
    op.create_table('pursuit_analysis_company_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('legacy_company_profile_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_only_count', sa.Integer(), nullable=False),
    sa.Column('file_backed_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("snapshot_sha256 ~ '^[0-9a-f]{64}$'", name='ck_analysis_company_snapshot_sha'),
    sa.CheckConstraint('metadata_only_count >= 0 AND file_backed_count >= 0', name='ck_analysis_company_snapshot_counts'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['pursuit_analysis_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['legacy_company_profile_id'], ['company_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id')
    )
    op.create_table('pursuit_analysis_pack_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('item_kind', sa.String(length=20), nullable=False),
    sa.Column('provenance', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('file_type', sa.String(length=150), nullable=True),
    sa.Column('private_document_id', sa.UUID(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('processing_result_id', sa.UUID(), nullable=True),
    sa.Column('processing_result_sha256', sa.String(length=64), nullable=True),
    sa.Column('tender_document_id', sa.UUID(), nullable=True),
    sa.Column('identity_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('analyzed_text', sa.Text(), nullable=False),
    sa.Column('analyzed_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('page_count_known', sa.Boolean(), nullable=False),
    sa.Column('locator_type', sa.String(length=30), nullable=False),
    sa.Column('locator_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(item_kind = 'PRIVATE' AND provenance = 'ORGANIZATION_PRIVATE_UPLOAD' AND private_document_id IS NOT NULL AND document_version_id IS NOT NULL AND version_number IS NOT NULL AND processing_result_id IS NOT NULL AND processing_result_sha256 IS NOT NULL AND tender_document_id IS NULL) OR (item_kind = 'SOURCE' AND provenance = 'SHARED_SOURCE' AND tender_document_id IS NOT NULL AND private_document_id IS NULL AND document_version_id IS NULL AND version_number IS NULL AND processing_result_id IS NULL AND processing_result_sha256 IS NULL)", name='ck_analysis_pack_item_identity_shape'),
    sa.CheckConstraint("analyzed_text_sha256 ~ '^[0-9a-f]{64}$'", name='ck_analysis_pack_item_text_sha'),
    sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name='ck_analysis_pack_item_content_sha'),
    sa.CheckConstraint("identity_sha256 ~ '^[0-9a-f]{64}$'", name='ck_analysis_pack_item_identity_sha'),
    sa.CheckConstraint("item_kind IN ('PRIVATE','SOURCE')", name='ck_analysis_pack_item_kind'),
    sa.CheckConstraint('page_count IS NULL OR page_count >= 1', name='ck_analysis_pack_item_pages'),
    sa.CheckConstraint('page_count_known = (page_count IS NOT NULL)', name='ck_analysis_pack_item_page_truth'),
    sa.ForeignKeyConstraint(['document_version_id'], ['private_document_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pack_id'], ['pursuit_analysis_packs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['private_document_id'], ['private_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processing_result_id'], ['private_document_processing_results.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tender_document_id'], ['tender_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id', 'identity_sha256', name='uq_analysis_pack_item_identity'),
    sa.UniqueConstraint('pack_id', 'ordinal', name='uq_analysis_pack_item_ordinal')
    )
    op.create_index('ix_analysis_pack_items_pack', 'pursuit_analysis_pack_items', ['pack_id', 'ordinal'], unique=False)
    op.create_table('pursuit_analysis_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('pack_item_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('distinction', sa.String(length=30), nullable=False),
    sa.Column('education_qualification', sa.Text(), nullable=True),
    sa.Column('general_experience', sa.Text(), nullable=True),
    sa.Column('specific_experience', sa.Text(), nullable=True),
    sa.Column('relevant_assignments', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_travel', sa.Text(), nullable=True),
    sa.Column('expected_effort', sa.Text(), nullable=True),
    sa.Column('assignment_dates', sa.Text(), nullable=True),
    sa.Column('source_span', sa.Text(), nullable=False),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_quote', sa.Text(), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('coverage_state', sa.String(length=40), nullable=False),
    sa.Column('review_state', sa.String(length=30), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('generated_interpretation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("coverage_state IN ('SUPPORTED', 'PARTIAL', 'GAP', 'EVIDENCE_MISSING', 'NEEDS_INTERPRETATION', 'NOT_APPLICABLE', 'LATER_STAGE_OBLIGATION')", name='ck_pursuit_position_coverage'),
    sa.CheckConstraint("distinction IN ('MANDATORY','SCORED')", name='ck_pursuit_position_distinction'),
    sa.CheckConstraint("review_state IN ('PROVISIONAL','CONFIRMED','CORRECTED')", name='ck_pursuit_position_review'),
    sa.CheckConstraint('extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)', name='ck_pursuit_position_confidence'),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 1', name='ck_pursuit_position_quantity'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['pursuit_analysis_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pack_item_id'], ['pursuit_analysis_pack_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pursuit_positions_run_state', 'pursuit_analysis_positions', ['analysis_run_id', 'coverage_state'], unique=False)
    op.create_table('pursuit_analysis_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('pack_item_id', sa.UUID(), nullable=False),
    sa.Column('source_span', sa.Text(), nullable=False),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_quote', sa.Text(), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('normalized_requirement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('stage_scope', sa.String(length=100), nullable=False),
    sa.Column('distinction', sa.String(length=30), nullable=False),
    sa.Column('predicate_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contribution_rule', sa.Text(), nullable=True),
    sa.Column('coverage_state', sa.String(length=40), nullable=False),
    sa.Column('review_state', sa.String(length=30), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('generated_interpretation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("coverage_state IN ('SUPPORTED', 'PARTIAL', 'GAP', 'EVIDENCE_MISSING', 'NEEDS_INTERPRETATION', 'NOT_APPLICABLE', 'LATER_STAGE_OBLIGATION')", name='ck_pursuit_requirement_coverage'),
    sa.CheckConstraint("distinction IN ('MANDATORY','SCORED','INFORMATIONAL')", name='ck_pursuit_requirement_distinction'),
    sa.CheckConstraint("review_state IN ('PROVISIONAL','CONFIRMED','CORRECTED')", name='ck_pursuit_requirement_review'),
    sa.CheckConstraint('extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)', name='ck_pursuit_requirement_confidence'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['pursuit_analysis_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pack_item_id'], ['pursuit_analysis_pack_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pursuit_requirements_run_state', 'pursuit_analysis_requirements', ['analysis_run_id', 'coverage_state'], unique=False)
    op.create_table('pursuit_analysis_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('source_pack_item_id', sa.UUID(), nullable=False),
    sa.Column('missing_contribution', sa.Text(), nullable=False),
    sa.Column('coverage_state', sa.String(length=40), nullable=False),
    sa.Column('resolution_category', sa.String(length=40), nullable=False),
    sa.Column('review_state', sa.String(length=30), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("coverage_state IN ('SUPPORTED', 'PARTIAL', 'GAP', 'EVIDENCE_MISSING', 'NEEDS_INTERPRETATION', 'NOT_APPLICABLE', 'LATER_STAGE_OBLIGATION')", name='ck_pursuit_gap_coverage'),
    sa.CheckConstraint("resolution_category IN ('COMPANY_EVIDENCE','PARTNER_FIRM','EXPERT','CLARIFICATION','HUMAN_INTERPRETATION')", name='ck_pursuit_gap_resolution'),
    sa.CheckConstraint("review_state IN ('PROVISIONAL','CONFIRMED','CORRECTED')", name='ck_pursuit_gap_review'),
    sa.CheckConstraint('(requirement_id IS NOT NULL) <> (position_id IS NOT NULL)', name='ck_pursuit_gap_single_target'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['pursuit_analysis_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['pursuit_analysis_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['pursuit_analysis_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_pack_item_id'], ['pursuit_analysis_pack_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pursuit_gaps_run_state', 'pursuit_analysis_gaps', ['analysis_run_id', 'coverage_state'], unique=False)
    op.create_table('pursuit_analysis_item_lineage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('target_kind', sa.String(length=20), nullable=False),
    sa.Column('prior_requirement_id', sa.UUID(), nullable=True),
    sa.Column('current_requirement_id', sa.UUID(), nullable=True),
    sa.Column('prior_position_id', sa.UUID(), nullable=True),
    sa.Column('current_position_id', sa.UUID(), nullable=True),
    sa.Column('actor_membership_id', sa.UUID(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(target_kind = 'REQUIREMENT' AND prior_requirement_id IS NOT NULL AND current_requirement_id IS NOT NULL AND prior_position_id IS NULL AND current_position_id IS NULL) OR (target_kind = 'POSITION' AND prior_position_id IS NOT NULL AND current_position_id IS NOT NULL AND prior_requirement_id IS NULL AND current_requirement_id IS NULL)", name='ck_analysis_lineage_shape'),
    sa.CheckConstraint("(target_kind = 'REQUIREMENT' AND prior_requirement_id IS DISTINCT FROM current_requirement_id) OR (target_kind = 'POSITION' AND prior_position_id IS DISTINCT FROM current_position_id)", name='ck_analysis_lineage_distinct'),
    sa.ForeignKeyConstraint(['actor_membership_id', 'organization_id'], ['memberships.id', 'memberships.organization_id'], name='fk_analysis_lineage_actor_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_position_id'], ['pursuit_analysis_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_requirement_id'], ['pursuit_analysis_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prior_position_id'], ['pursuit_analysis_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prior_requirement_id'], ['pursuit_analysis_requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prior_position_id', 'current_position_id', name='uq_analysis_position_lineage'),
    sa.UniqueConstraint('prior_requirement_id', 'current_requirement_id', name='uq_analysis_requirement_lineage')
    )
    op.create_table('pursuit_analysis_review_assertions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('target_kind', sa.String(length=20), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('gap_id', sa.UUID(), nullable=True),
    sa.Column('actor_membership_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_assertion_id', sa.UUID(), nullable=True),
    sa.Column('prior_coverage_state', sa.String(length=40), nullable=True),
    sa.Column('new_coverage_state', sa.String(length=40), nullable=False),
    sa.Column('prior_review_state', sa.String(length=30), nullable=False),
    sa.Column('new_review_state', sa.String(length=30), nullable=False),
    sa.Column('corrected_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("new_coverage_state IN ('SUPPORTED', 'PARTIAL', 'GAP', 'EVIDENCE_MISSING', 'NEEDS_INTERPRETATION', 'NOT_APPLICABLE', 'LATER_STAGE_OBLIGATION')", name='ck_analysis_assertion_new_coverage'),
    sa.CheckConstraint("new_review_state IN ('CONFIRMED','CORRECTED')", name='ck_analysis_assertion_new_review'),
    sa.CheckConstraint("prior_coverage_state IS NULL OR prior_coverage_state IN ('SUPPORTED', 'PARTIAL', 'GAP', 'EVIDENCE_MISSING', 'NEEDS_INTERPRETATION', 'NOT_APPLICABLE', 'LATER_STAGE_OBLIGATION')", name='ck_analysis_assertion_prior_coverage'),
    sa.CheckConstraint("prior_review_state IN ('PROVISIONAL','CONFIRMED','CORRECTED')", name='ck_analysis_assertion_prior_review'),
    sa.CheckConstraint("target_kind IN ('REQUIREMENT','POSITION','GAP')", name='ck_analysis_assertion_kind'),
    sa.CheckConstraint("(target_kind = 'REQUIREMENT' AND requirement_id IS NOT NULL AND position_id IS NULL AND gap_id IS NULL) OR (target_kind = 'POSITION' AND position_id IS NOT NULL AND requirement_id IS NULL AND gap_id IS NULL) OR (target_kind = 'GAP' AND gap_id IS NOT NULL AND requirement_id IS NULL AND position_id IS NULL)", name='ck_analysis_assertion_single_target'),
    sa.ForeignKeyConstraint(['actor_membership_id', 'organization_id'], ['memberships.id', 'memberships.organization_id'], name='fk_analysis_assertion_actor_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['pursuit_analysis_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gap_id'], ['pursuit_analysis_gaps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['pursuit_analysis_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['pursuit_analysis_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_assertion_id'], ['pursuit_analysis_review_assertions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_assertions_run_created', 'pursuit_analysis_review_assertions', ['analysis_run_id', 'created_at'], unique=False)
    op.execute(
        """
        CREATE FUNCTION reject_w4_analysis_history_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'W4 sealed analysis history is immutable';
        END;
        $$
        """
    )
    for table_name in (
        "pursuit_analysis_packs",
        "pursuit_analysis_pack_items",
        "pursuit_analysis_company_snapshots",
        "pursuit_analysis_requirements",
        "pursuit_analysis_positions",
        "pursuit_analysis_gaps",
        "pursuit_analysis_review_assertions",
        "pursuit_analysis_item_lineage",
    ):
        op.execute(
            f"CREATE TRIGGER {table_name}_append_only BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION reject_w4_analysis_history_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table_name in (
        "pursuit_analysis_item_lineage",
        "pursuit_analysis_review_assertions",
        "pursuit_analysis_gaps",
        "pursuit_analysis_positions",
        "pursuit_analysis_requirements",
        "pursuit_analysis_company_snapshots",
        "pursuit_analysis_pack_items",
        "pursuit_analysis_packs",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_append_only ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS reject_w4_analysis_history_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_assertions_run_created', table_name='pursuit_analysis_review_assertions')
    op.drop_table('pursuit_analysis_review_assertions')
    op.drop_table('pursuit_analysis_item_lineage')
    op.drop_index('ix_pursuit_gaps_run_state', table_name='pursuit_analysis_gaps')
    op.drop_table('pursuit_analysis_gaps')
    op.drop_index('ix_pursuit_requirements_run_state', table_name='pursuit_analysis_requirements')
    op.drop_table('pursuit_analysis_requirements')
    op.drop_index('ix_pursuit_positions_run_state', table_name='pursuit_analysis_positions')
    op.drop_table('pursuit_analysis_positions')
    op.drop_index('ix_analysis_pack_items_pack', table_name='pursuit_analysis_pack_items')
    op.drop_table('pursuit_analysis_pack_items')
    op.drop_table('pursuit_analysis_company_snapshots')
    op.drop_index('ix_analysis_runs_pursuit_created', table_name='pursuit_analysis_runs')
    op.drop_index('ix_analysis_runs_dispatch', table_name='pursuit_analysis_runs')
    op.drop_table('pursuit_analysis_runs')
    op.drop_index('ix_analysis_packs_pursuit_created', table_name='pursuit_analysis_packs')
    op.drop_table('pursuit_analysis_packs')
    # ### end Alembic commands ###
