"""Add dynamic compliance ontology and risk override log

Revision ID: 619f79030fe7
Revises: 20260227_0001_google_oauth_cutover
Create Date: 2026-03-01 22:46:49.303957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619f79030fe7'
down_revision: Union[str, None] = '20260227_0001_google_oauth_cutover'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
