"""Country -> capital time zone (IANA), for deadlines published without a zone.

GENERATED from tzdata 2026c (iso3166.tab, zone.tab) by the integration session;
multi-zone countries use their capital's zone (AR, AU, BR, CA, CD, CL, CN, CY, DE, EC, ES, FM, GL, ID, KI, KZ, MH, MN, MX, MY, NZ, PF, PG, PS, PT, RU, UA, US, UZ);
source spellings (World Bank, GIZ, EBRD) are aliases. Regions ("Central Asia",
"Western and Central Africa") are deliberately absent: they have no single zone.

Keys are ``country.strip().lower()`` so the Python lookup and the PostgreSQL
``lower(btrim(country))`` lookup (app.core.deadline_truth) agree.
"""

from __future__ import annotations

from types import MappingProxyType

COUNTRY_TIMEZONES = MappingProxyType({
    'afghanistan': 'Asia/Kabul',
    'albania': 'Europe/Tirane',
    'algeria': 'Africa/Algiers',
    'andorra': 'Europe/Andorra',
    'angola': 'Africa/Luanda',
    'anguilla': 'America/Anguilla',
    'antigua & barbuda': 'America/Antigua',
    'argentina': 'America/Argentina/Buenos_Aires',
    'armenia': 'Asia/Yerevan',
    'aruba': 'America/Aruba',
    'australia': 'Australia/Sydney',
    'austria': 'Europe/Vienna',
    'azerbaijan': 'Asia/Baku',
    'bahamas': 'America/Nassau',
    'bahamas, the': 'America/Nassau',
    'bahrain': 'Asia/Bahrain',
    'bangladesh': 'Asia/Dhaka',
    'barbados': 'America/Barbados',
    'belarus': 'Europe/Minsk',
    'belgium': 'Europe/Brussels',
    'belize': 'America/Belize',
    'benin': 'Africa/Porto-Novo',
    'bermuda': 'Atlantic/Bermuda',
    'bhutan': 'Asia/Thimphu',
    'bolivia': 'America/La_Paz',
    'bosnia & herzegovina': 'Europe/Sarajevo',
    'botswana': 'Africa/Gaborone',
    'brazil': 'America/Sao_Paulo',
    'britain (uk)': 'Europe/London',
    'british indian ocean territory': 'Indian/Chagos',
    'brunei': 'Asia/Brunei',
    'brunei darussalam': 'Asia/Brunei',
    'bulgaria': 'Europe/Sofia',
    'burkina faso': 'Africa/Ouagadougou',
    'burma': 'Asia/Yangon',
    'burundi': 'Africa/Bujumbura',
    'cabo verde': 'Atlantic/Cape_Verde',
    'cambodia': 'Asia/Phnom_Penh',
    'cameroon': 'Africa/Douala',
    'canada': 'America/Toronto',
    'cape verde': 'Atlantic/Cape_Verde',
    'caribbean nl': 'America/Kralendijk',
    'cayman islands': 'America/Cayman',
    'central african rep.': 'Africa/Bangui',
    'chad': 'Africa/Ndjamena',
    'chile': 'America/Santiago',
    'china': 'Asia/Shanghai',
    'christmas island': 'Indian/Christmas',
    'cocos (keeling) islands': 'Indian/Cocos',
    'colombia': 'America/Bogota',
    'comoros': 'Indian/Comoro',
    'congo': 'Africa/Brazzaville',
    'congo (dem. rep.)': 'Africa/Kinshasa',
    'congo (rep.)': 'Africa/Brazzaville',
    'congo, dem. rep.': 'Africa/Kinshasa',
    'congo, democratic republic of': 'Africa/Kinshasa',
    'congo, rep.': 'Africa/Brazzaville',
    'congo, republic of': 'Africa/Brazzaville',
    'cook islands': 'Pacific/Rarotonga',
    'costa rica': 'America/Costa_Rica',
    "cote d'ivoire": 'Africa/Abidjan',
    'croatia': 'Europe/Zagreb',
    'cuba': 'America/Havana',
    'curacao': 'America/Curacao',
    'curaçao': 'America/Curacao',
    'cyprus': 'Asia/Nicosia',
    'czech republic': 'Europe/Prague',
    'czechia': 'Europe/Prague',
    "côte d'ivoire": 'Africa/Abidjan',
    'côte d’ivoire': 'Africa/Abidjan',
    'democratic republic of the congo': 'Africa/Kinshasa',
    'denmark': 'Europe/Copenhagen',
    'djibouti': 'Africa/Djibouti',
    'dominica': 'America/Dominica',
    'dominican republic': 'America/Santo_Domingo',
    'drc': 'Africa/Kinshasa',
    'east timor': 'Asia/Dili',
    'ecuador': 'America/Guayaquil',
    'egypt': 'Africa/Cairo',
    'egypt, arab republic of': 'Africa/Cairo',
    'el salvador': 'America/El_Salvador',
    'equatorial guinea': 'Africa/Malabo',
    'eritrea': 'Africa/Asmara',
    'estonia': 'Europe/Tallinn',
    'eswatini': 'Africa/Mbabane',
    'eswatini (swaziland)': 'Africa/Mbabane',
    'ethiopia': 'Africa/Addis_Ababa',
    'falkland islands': 'Atlantic/Stanley',
    'faroe islands': 'Atlantic/Faroe',
    'fiji': 'Pacific/Fiji',
    'finland': 'Europe/Helsinki',
    'france': 'Europe/Paris',
    'french guiana': 'America/Cayenne',
    'french polynesia': 'Pacific/Tahiti',
    'french s. terr.': 'Indian/Kerguelen',
    'gabon': 'Africa/Libreville',
    'gambia': 'Africa/Banjul',
    'gambia, the': 'Africa/Banjul',
    'georgia': 'Asia/Tbilisi',
    'germany': 'Europe/Berlin',
    'ghana': 'Africa/Accra',
    'gibraltar': 'Europe/Gibraltar',
    'greece': 'Europe/Athens',
    'greenland': 'America/Nuuk',
    'grenada': 'America/Grenada',
    'guadeloupe': 'America/Guadeloupe',
    'guam': 'Pacific/Guam',
    'guatemala': 'America/Guatemala',
    'guernsey': 'Europe/Guernsey',
    'guinea': 'Africa/Conakry',
    'guinea-bissau': 'Africa/Bissau',
    'guyana': 'America/Guyana',
    'haiti': 'America/Port-au-Prince',
    'honduras': 'America/Tegucigalpa',
    'hong kong': 'Asia/Hong_Kong',
    'hong kong sar, china': 'Asia/Hong_Kong',
    'hungary': 'Europe/Budapest',
    'iceland': 'Atlantic/Reykjavik',
    'india': 'Asia/Kolkata',
    'indonesia': 'Asia/Jakarta',
    'iran': 'Asia/Tehran',
    'iran, islamic republic of': 'Asia/Tehran',
    'iraq': 'Asia/Baghdad',
    'ireland': 'Europe/Dublin',
    'isle of man': 'Europe/Isle_of_Man',
    'israel': 'Asia/Jerusalem',
    'italy': 'Europe/Rome',
    'ivory coast': 'Africa/Abidjan',
    'jamaica': 'America/Jamaica',
    'japan': 'Asia/Tokyo',
    'jersey': 'Europe/Jersey',
    'jordan': 'Asia/Amman',
    'kazakhstan': 'Asia/Almaty',
    'kenya': 'Africa/Nairobi',
    'kiribati': 'Pacific/Tarawa',
    'korea (north)': 'Asia/Pyongyang',
    'korea (south)': 'Asia/Seoul',
    "korea, democratic people's republic of": 'Asia/Pyongyang',
    'korea, republic of': 'Asia/Seoul',
    'kosovo': 'Europe/Belgrade',
    'kuwait': 'Asia/Kuwait',
    'kyrgyz republic': 'Asia/Bishkek',
    'kyrgyzstan': 'Asia/Bishkek',
    'lao pdr': 'Asia/Vientiane',
    "lao people's democratic republic": 'Asia/Vientiane',
    'laos': 'Asia/Vientiane',
    'latvia': 'Europe/Riga',
    'lebanon': 'Asia/Beirut',
    'lesotho': 'Africa/Maseru',
    'liberia': 'Africa/Monrovia',
    'libya': 'Africa/Tripoli',
    'liechtenstein': 'Europe/Vaduz',
    'lithuania': 'Europe/Vilnius',
    'luxembourg': 'Europe/Luxembourg',
    'macao sar, china': 'Asia/Macau',
    'macau': 'Asia/Macau',
    'macedonia': 'Europe/Skopje',
    'madagascar': 'Indian/Antananarivo',
    'malawi': 'Africa/Blantyre',
    'malaysia': 'Asia/Kuala_Lumpur',
    'maldives': 'Indian/Maldives',
    'mali': 'Africa/Bamako',
    'malta': 'Europe/Malta',
    'marshall islands': 'Pacific/Majuro',
    'martinique': 'America/Martinique',
    'mauritania': 'Africa/Nouakchott',
    'mauritius': 'Indian/Mauritius',
    'mayotte': 'Indian/Mayotte',
    'mexico': 'America/Mexico_City',
    'micronesia': 'Pacific/Pohnpei',
    'micronesia, federated states of': 'Pacific/Pohnpei',
    'moldova': 'Europe/Chisinau',
    'monaco': 'Europe/Monaco',
    'mongolia': 'Asia/Ulaanbaatar',
    'montenegro': 'Europe/Podgorica',
    'montserrat': 'America/Montserrat',
    'morocco': 'Africa/Casablanca',
    'mozambique': 'Africa/Maputo',
    'myanmar (burma)': 'Asia/Yangon',
    'namibia': 'Africa/Windhoek',
    'nauru': 'Pacific/Nauru',
    'nepal': 'Asia/Kathmandu',
    'netherlands': 'Europe/Amsterdam',
    'new caledonia': 'Pacific/Noumea',
    'new zealand': 'Pacific/Auckland',
    'nicaragua': 'America/Managua',
    'niger': 'Africa/Niamey',
    'nigeria': 'Africa/Lagos',
    'niue': 'Pacific/Niue',
    'norfolk island': 'Pacific/Norfolk',
    'north korea': 'Asia/Pyongyang',
    'north macedonia': 'Europe/Skopje',
    'northern mariana islands': 'Pacific/Saipan',
    'norway': 'Europe/Oslo',
    'oman': 'Asia/Muscat',
    'pakistan': 'Asia/Karachi',
    'palau': 'Pacific/Palau',
    'palestine': 'Asia/Hebron',
    'panama': 'America/Panama',
    'papua new guinea': 'Pacific/Port_Moresby',
    'paraguay': 'America/Asuncion',
    'peru': 'America/Lima',
    'philippines': 'Asia/Manila',
    'pitcairn': 'Pacific/Pitcairn',
    'poland': 'Europe/Warsaw',
    'portugal': 'Europe/Lisbon',
    'puerto rico': 'America/Puerto_Rico',
    'qatar': 'Asia/Qatar',
    'republic of the congo': 'Africa/Brazzaville',
    'romania': 'Europe/Bucharest',
    'russia': 'Europe/Moscow',
    'russian federation': 'Europe/Moscow',
    'rwanda': 'Africa/Kigali',
    'réunion': 'Indian/Reunion',
    'samoa (american)': 'Pacific/Pago_Pago',
    'samoa (western)': 'Pacific/Apia',
    'san marino': 'Europe/San_Marino',
    'sao tome & principe': 'Africa/Sao_Tome',
    'sao tome and principe': 'Africa/Sao_Tome',
    'saudi arabia': 'Asia/Riyadh',
    'senegal': 'Africa/Dakar',
    'serbia': 'Europe/Belgrade',
    'seychelles': 'Indian/Mahe',
    'sierra leone': 'Africa/Freetown',
    'singapore': 'Asia/Singapore',
    'sint maarten': 'America/Lower_Princes',
    'slovak republic': 'Europe/Bratislava',
    'slovakia': 'Europe/Bratislava',
    'slovenia': 'Europe/Ljubljana',
    'solomon islands': 'Pacific/Guadalcanal',
    'somalia': 'Africa/Mogadishu',
    'somalia, federal republic of': 'Africa/Mogadishu',
    'south africa': 'Africa/Johannesburg',
    'south georgia & the south sandwich islands': 'Atlantic/South_Georgia',
    'south korea': 'Asia/Seoul',
    'south sudan': 'Africa/Juba',
    'spain': 'Europe/Madrid',
    'sri lanka': 'Asia/Colombo',
    'st barthelemy': 'America/St_Barthelemy',
    'st helena': 'Atlantic/St_Helena',
    'st kitts & nevis': 'America/St_Kitts',
    'st kitts and nevis': 'America/St_Kitts',
    'st lucia': 'America/St_Lucia',
    'st maarten': 'America/Lower_Princes',
    'st maarten (dutch)': 'America/Lower_Princes',
    'st martin (french)': 'America/Marigot',
    'st pierre & miquelon': 'America/Miquelon',
    'st vincent': 'America/St_Vincent',
    'st vincent and the grenadines': 'America/St_Vincent',
    'st. kitts and nevis': 'America/St_Kitts',
    'st. lucia': 'America/St_Lucia',
    'st. maarten': 'America/Lower_Princes',
    'st. vincent and the grenadines': 'America/St_Vincent',
    'sudan': 'Africa/Khartoum',
    'suriname': 'America/Paramaribo',
    'svalbard & jan mayen': 'Arctic/Longyearbyen',
    'swaziland': 'Africa/Mbabane',
    'sweden': 'Europe/Stockholm',
    'switzerland': 'Europe/Zurich',
    'syria': 'Asia/Damascus',
    'syrian arab republic': 'Asia/Damascus',
    'são tomé and príncipe': 'Africa/Sao_Tome',
    'taiwan': 'Asia/Taipei',
    'taiwan, china': 'Asia/Taipei',
    'tajikistan': 'Asia/Dushanbe',
    'tanzania': 'Africa/Dar_es_Salaam',
    'thailand': 'Asia/Bangkok',
    'the gambia': 'Africa/Banjul',
    'timor-leste': 'Asia/Dili',
    'togo': 'Africa/Lome',
    'tokelau': 'Pacific/Fakaofo',
    'tonga': 'Pacific/Tongatapu',
    'trinidad & tobago': 'America/Port_of_Spain',
    'tunisia': 'Africa/Tunis',
    'turkey': 'Europe/Istanbul',
    'turkiye': 'Europe/Istanbul',
    'turkmenistan': 'Asia/Ashgabat',
    'turks & caicos is': 'America/Grand_Turk',
    'tuvalu': 'Pacific/Funafuti',
    'türkiye': 'Europe/Istanbul',
    'uganda': 'Africa/Kampala',
    'ukraine': 'Europe/Kyiv',
    'united arab emirates': 'Asia/Dubai',
    'united kingdom': 'Europe/London',
    'united states': 'America/New_York',
    'uruguay': 'America/Montevideo',
    'uzbekistan': 'Asia/Tashkent',
    'vanuatu': 'Pacific/Efate',
    'vatican city': 'Europe/Vatican',
    'venezuela': 'America/Caracas',
    'venezuela, rb': 'America/Caracas',
    'venezuela, republica bolivariana de': 'America/Caracas',
    'viet nam': 'Asia/Ho_Chi_Minh',
    'vietnam': 'Asia/Ho_Chi_Minh',
    'virgin islands (uk)': 'America/Tortola',
    'virgin islands (us)': 'America/St_Thomas',
    'wallis & futuna': 'Pacific/Wallis',
    'west bank and gaza': 'Asia/Hebron',
    'western sahara': 'Africa/El_Aaiun',
    'yemen': 'Asia/Aden',
    'yemen, republic of': 'Asia/Aden',
    'zambia': 'Africa/Lusaka',
    'zimbabwe': 'Africa/Harare',
    'åland islands': 'Europe/Mariehamn',
})


def country_timezone(country: str | None) -> str | None:
    """IANA zone of the country's capital, or None when the country is unknown."""
    if not country:
        return None
    return COUNTRY_TIMEZONES.get(country.strip().lower())
